name: Discord Notification on New Extension

on:
  push:
    branches:
      - main
    paths:
      - 'apk/**'
      - 'index.min.json'

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Discord Notification Script
        env:
          BEFORE_SHA: ${{ github.event.before }}
          AFTER_SHA: ${{ github.event.after }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          python .github/scripts/notify.py
